export const apiv3 = 'https://testnet.binance.vision/api/v3'
// export const apiv3 = 'https://api.binance.com/api/v3'
// export const ws = 'wss://testnet.binance.vision/ws'
export const ws = 'wss://stream.binance.com:9443/ws'
// export const stream = 'wss://testnet.binance.vision/stream'
export const stream = 'wss://stream.binance.com:9443/stream'
